services:
  db:
      image: postgres:13.0-alpine
      volumes:
        - db-data:/var/lib/postgresql/data
      env_file:
        - ./database.env
      ports:
        - "5432:5432"
volumes:
  db-data: